### ISSUE TITLE
seeInOpenedEmailBody -> interprets emails as plain text instead of html

### ISSUE THREAD

**Issue by duronrulez** [ericmartel/codeception-email-mailhog#1]
Hello,

There seems to be a problem in which when you try to validate contents of an HTML email using seeInOpenedEmailBody it tries to validate them against the plain text version of the email:

```
$I->seeInOpenedEmailBody("So you’ve");

<p style=3D"line-height:1.3; margin:12px 0 0px; font-size: 9pt; color:=
#333333;">So you=E2=80=99ve ...: <br/>
```

Is there any way to force the rendering of the emails to be HTML instead of plain text?

**Comment by duronrulez** [comment]
This seems to be a mailhog issue, and not related to your module.

**Comment by ericmartel** [comment]
Thank you for reporting the issue and thank you even more for the investigation afterwards!

**Comment by fnagel** [comment]
@duronrulez Did you find a solution for this? I'm trying to grab a link from the email. Any ideas?
