### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jaspernbrouwer** [ericmartel/codeception-email-mailhog#10]
Since the last release (`1.0.3`, 27-12-2016) there are 4 merged PRs, 11 commits on master. Looks like a great moment to have a new release 😄 

PS: I'm running into the issue that #5 fixed, but I need to point composer to `dev-master` to be able to use it.

**Comment by ericmartel** [comment]
Indeed!

Sorry about that, I'll try to create a new release over lunch

**Comment by ericmartel** [comment]
Did it work for you?  (Sorry I don't use this package myself)

**Comment by jaspernbrouwer** [comment]
I can see the tag (`1.0.4`) on Github, but [Packagist](https://packagist.org/packages/ericmartel/codeception-email-mailhog) hasn't picked it up. Did you enable the service hook?

**Comment by ericmartel** [comment]
Should be fixed now!

Thanks :)
