### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Dejfik** [ericmartel/codeception-email-mailhog#15]
Hi,
it took me a while to figure out, how the timeout works. I thought, that timeout configuration in codeception yml files would work for this, but they don´t.

`        - MailHog:`
`            url: '165.227.150.229'`
`            port: 80`
`            pageload_timeout: 10`
`            connection_timeout: 10`
`            request_timeout: 10`

I had all the timeout settings set for around 10 seconds but fetchEmails() timeouted after 1000ms everytime.
So after some time i found it here:
src/MailHog.php  line 74
`$this->mailhog = new \GuzzleHttp\Client(['base_uri' => $url, 'timeout' => 1.0]);`
I just want to post this issue here if anyone would look for the same thing.
Thanks

**Comment by ericmartel** [comment]
Hi

Sorry for the inconvenience.

I am not currently setup to test anything with Mailhog, but could you try these changes locally and see if you can get the behavior you'd be expecting?

Mailhog.php
line 61
```
protected $config = array('url', 'port', 'guzzleRequestOptions', 'deleteEmailsAfterScenario', 'timeout');
```

line 74
```
$timeout = 1.0;
if(isset($this->config['timeout']))
    $timeout = $this->config['timeout'];
$this->mailhog = new \GuzzleHttp\Client(['base_uri' => $url, 'timeout' => $timeout]);
```

Thanks

**Comment by Dejfik** [comment]
Hi,
sorry for the delay, I had to do other stuff. But i tried what you suggested and it works like a charm.
I modified Mailhog.php and then tested various timeouts.
So now it works exactly as I expected, in my acceptance.suite.yml I have url, port and timeout options.
I am closing this issue.
Thank you
